# Generated by Django 5.0.6 on 2025-02-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_testcase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='sample_input',
            new_name='sample_testcases',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sample_output',
        ),
    ]
