# Generated by Django 5.0.6 on 2025-02-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_rename_sample_input_problem_sample_testcases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='cpp_code_prefix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='cpp_function_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='cpp_main',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='java_code_prefix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='java_function_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='java_main',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='python_code_prefix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='python_function_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='python_main',
            field=models.TextField(blank=True, null=True),
        ),
    ]
