# Generated by Django 5.1.4 on 2025-02-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_question_rename_created_at_submission_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.JSONField(),
        ),
    ]
