# Generated by Django 5.1.4 on 2025-02-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_alter_testcase_input_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.JSONField(),
        ),
    ]
