# Generated by Django 5.1.4 on 2025-02-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='problem',
            name='expected_cpp_signature',
            field=models.CharField(default='vector<int> twoSum(vector<int>& nums, int target)', max_length=200),
        ),
        migrations.AddField(
            model_name='problem',
            name='expected_java_signature',
            field=models.CharField(default='public int[] twoSum(int[] nums, int target)', max_length=200),
        ),
        migrations.AddField(
            model_name='problem',
            name='expected_python_signature',
            field=models.CharField(default='def twoSum(nums, target):', max_length=200),
        ),
    ]
