# Generated by Django 5.1.4 on 2025-02-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_problem_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='expected_cpp_signature',
            field=models.CharField(default='vector<int> twoSum(vector<int>& nums, int target)', max_length=500),
        ),
        migrations.AlterField(
            model_name='problem',
            name='expected_java_signature',
            field=models.CharField(default='public int[] twoSum(int[] nums, int target)', max_length=500),
        ),
        migrations.AlterField(
            model_name='problem',
            name='expected_python_signature',
            field=models.CharField(default='def twoSum(nums, target):', max_length=500),
        ),
    ]
