# Generated by Django 5.1.4 on 2025-02-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_problem_expected_cpp_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='constraints',
            field=models.TextField(null=True),
        ),
    ]
