# Generated by Django 5.1.4 on 2025-02-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_problem_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='expected_cpp_signature',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='expected_java_signature',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='expected_python_signature',
            field=models.TextField(),
        ),
    ]
